spring:
  datasource:
    url: jdbc:mysql://180.106.83.239:46986/cxjk_xspt?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Cloud@18915898007
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 10000
      idleTimeout: 50000
      minimumIdle: 2
      maximumPoolSize: 5
      connectionTestQuery: select 1
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

#sprongboot健康监控
management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    logfile:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20  # 心跳检测检测与续约时间
    lease-expiration-duration-in-seconds: 30 # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 15
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://YG0475:4c1a09@localhost:8888/eureka/
    enabled: true


logging:
  level:
    root: info

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        circuitBreaker:
          requestVolumeThreshold: 20
          sleepWindowInMilliseconds: 5000
        isolation:
          thread:
            timeoutInMilliseconds: 15000


properties:
  filepath: f:\\contracts
  downloadpath: http://localhost:28080/tmpfile/