server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://10.30.20.212:8635/cxjk_xspt?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Cloud@kuw9d2d22
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      minimumIdle: 50
      maximumPoolSize: 100
      connectionTestQuery: select 1

boot:
  admin:
    client:
      url: http://10.30.50.146:8082


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    instanceId: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://YG0475:4c1a09@10.30.50.146:8090/eureka/

management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    logfile:
      enabled: true
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info

ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  ConnectTimeout: 10 #请求连接超时时间
  ReadTimeout: 0 #请求处理的超时时间
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有请求都进行重试默认是false
  ServerListRefreshInterval: 2000 #ribbon缓存时间

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        circuitBreaker:
          requestVolumeThreshold: 20
          sleepWindowInMilliseconds: 500
        isolation:
          thread:
            timeoutInMilliseconds: 100

properties:
  filepath: /mnt/program/apache-tomcat-8.5.32-business/webapps/tmpfile
  downloadpath: http://msp2.cxjk.com/tmpfile

