server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://180.106.83.239:46986/cxjk_xspt?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Cloud@18915898007
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 10000
      idleTimeout: 50000
      minimumIdle: 2
      maximumPoolSize: 5
      connectionTestQuery: select 1
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    instanceId: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://YG0475:4c1a09@localhost:8888/eureka/
    enabled: true

logging:
  level:
    root: info

#配置单个service的，也可以直接用全局就不用谢servicid
eds-base:
 ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  ConnectTimeout: 10 #请求连接超时时间
  ReadTimeout: 0 #请求处理的超时时间
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有请求都进行重试默认是false
  ServerListRefreshInterval: 2000 #ribbon缓存时间

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        circuitBreaker:
          requestVolumeThreshold: 20
          sleepWindowInMilliseconds: 5000
        isolation:
          thread:
            timeoutInMilliseconds: 5000

properties:
  filepath: f:\\contracts
  downloadpath: http://localhost:28080/tmpfile/