server:
  port: 8090

spring:
  #  datasource:
  #    url: jdbc:mysql://10.30.50.49:3306/cxjk?useUnicode=true&characterEncoding=utf-8&useSSL=true
  #    username: cxjk_safe
  #    password: =DK89234kdc(
  #    driver-class-name: com.mysql.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource
  boot:
    admin:
      client:
        url: http://10.30.50.146:8082

management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    logfile:
      enabled: true
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  #自我保护机制关闭
  enableSelfPreservation: false
  evictionIntervalTimerInMs: 3000
  useReadOnlyResponseCache: false
  response-cache-update-interval-ms: 10000
  response-cache-auto-expiration-in-seconds: 180
  leaseRenewalIntervalInSeconds: 5
  leaseExpirationDurationInSeconds: 10
  peer-node-read-timeout-ms: 1200
  instance:
    hostname: eureka1
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 90
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://YG0475:4c1a09@10.30.50.49:8090/eureka/
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true


